AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Use the cluster to transform subdomains into URLs using gau.


# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 180

Parameters:
  DeploymentEnvironment:
    Type: String
    Description: The environment you are deploying this stack in.
  DynamoDBSubdomainsTableStreamARN:
    Type: String
    Description: The ARN representing the DynamoDB table you wish to subscribe to.
  DalfoxUrlsQueueUrl:
    Type: String
    Description: The SQS queue URL to push URLs to the dalfox urls queue.
  DalfoxUrlsQueueArn:
    Type: String
    Description: The SQS queue ARN to grant the container access to the dalfox urls queue.
  ArjunParameterMiningQueueUrl:
    Type: String
    Description: The SQS queue URL to push URLs to the arjun parameter mining urls queue.
  ECSTaskExecutionRoleARN:
    Type: String
    Description: The ARN for the task execution role to container will use in the ECS cluster during execution.
  XHuntToolsContainerRepositoryName:
    Type: String
    Description: The ECR repository name for the xhunt-tools container. This should be any container used to run gau.
  JobQueue:
    Type: String
    Description: The job queue on the cluster to submit the job to.


Resources:
  GauSubdomainJobDispatcherFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
      - x86_64
      Policies: 
        - AWSLambdaSQSQueueExecutionRole
        - AWSBatchServiceEventTargetRole
      Environment:
        Variables:
            TASK_CLUSTER_JOB_QUEUE_ARN: !Ref JobQueue
            TASK_CLUSTER_GAU_SUBDOMAINS_JOB_DEFINITION_ARN: !Ref GauSubdomainsJobDefinition
            DALFOX_URLS_QUEUE: !Ref DalfoxUrlsQueueUrl
            ARJUN_PARAMETER_MINING_QUEUE: !Ref ArjunParameterMiningQueueUrl
      # Configure event source mappings
      # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-function-sqs.html
      Events:
        SubdomainsDynamoDB:
          Type: DynamoDB
          Properties:
            Enabled: true
            BatchSize: 1000
            StartingPosition: LATEST
            Stream: !Ref DynamoDBSubdomainsTableStreamARN

  ## IAM ##
  GauSubdomainsJobDefinitionRole:
    Type: AWS::IAM::Role
    Properties:
      Policies:
        - PolicyDocument: 
            Version: '2012-10-17'
            Statement:
            - Action: sqs:SendMessage
              Effect: Allow
              Resource: !Ref DalfoxUrlsQueueArn
          PolicyName: SendMessagesToDalfoxUrlsQueue
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
      RoleName: !Sub GauSubdomainsJobDefinitionRole-${DeploymentEnvironment}
      Tags:
        - Key: xhunt
          Value: task-cluster

  ## CLUSTER JOB DEFINITIONS ##
  GauSubdomainsJobDefinition:
    Type: AWS::Batch::JobDefinition
    Properties:
      ContainerProperties:
        Environment: []
        ExecutionRoleArn: !Ref ECSTaskExecutionRoleARN
        JobRoleArn: !GetAtt GauSubdomainsJobDefinitionRole.Arn
        FargatePlatformConfiguration:
          PlatformVersion: LATEST
        Image:
          !Join
            - ''
            - - !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/
              - !Ref  XHuntToolsContainerRepositoryName
              - :latest
        LinuxParameters:
          Devices: []
          InitProcessEnabled: false
          Tmpfs: []
        LogConfiguration:
          LogDriver: awslogs
          Options:
            awslogs-region: !Ref AWS::Region
            awslogs-group: /xhunt/task-cluster/gau-subdomains-to-urls
            awslogs-create-group: true
          SecretOptions: []
        MountPoints: []
        NetworkConfiguration:
          AssignPublicIp: ENABLED
        ReadonlyRootFilesystem: false
        ResourceRequirements:
        - Type: VCPU
          Value: '0.5'
        - Type: MEMORY
          Value: '2048'
        Secrets: []
        Ulimits: []
        User: root
        Volumes: []
      JobDefinitionName: GauSubdomainsToUrls
      Parameters: {}
      PlatformCapabilities:
      - FARGATE
      RetryStrategy:
        Attempts: 1
        EvaluateOnExit: []
      Tags: {}
      Timeout:
        AttemptDurationSeconds: 1800
      Type: container


Outputs:
  GauSubdomainsJobDefinitionARN:
    Value: !Ref GauSubdomainsJobDefinition
    Export:
      Name: GauSubdomainsJobDefinitionARN