AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  job-dispatcher

  Sample SAM Template for job-dispatcher

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 180

Parameters:
  ClusterSubnetID:
    Type: String
    Default: subnet-24a5095e
    Description: Enter the subnet ID you wish to deploy this cluster in.
  ClusterVPCID:
    Type: String
    Default: vpc-5475173c
    Description: >
      Enter the VPC ID you wish to deploy this cluster in. The default VPC is recommended.
      This is done so that a security group can be deployed. 


Resources:
  DalfoxUrlJobDispatcherServerlessApplication:
    Type: AWS::Serverless::Application
    Properties:
      Location: dalfox_url_job_dispatcher/template.yaml
      Parameters:
        ECSTaskExecutionRoleARN: !GetAtt ECSTaskExecutionRole.Arn
        XHuntToolsContainerRepositoryName: !Ref XHuntToolsRepository
        JobQueue: !Ref JobQueue

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Join:
        - ''
        - - ApplicationInsights-SAM-
          - Ref: AWS::StackName
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0

  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Fn::Join:
        - ''
        - - ApplicationInsights-SAM-
          - Ref: AWS::StackName
      AutoConfigurationEnabled: 'true'
    DependsOn: ApplicationResourceGroup

  ## ECR ##
  XHuntToolsRepository:
    Type: AWS::ECR::Repository
    Properties: 
      RepositoryName: xhunt-tools
      ImageScanningConfiguration: 
        ScanOnPush: true

  ## FARGATE CLUSTER ##
  BatchComputeEnvironment:
    Type: AWS::Batch::ComputeEnvironment
    Properties: 
      ComputeEnvironmentName: XHuntTaskComputeEnvironment
      ComputeResources:
          MaxvCpus: 8
          Subnets: 
            - !Ref ClusterSubnetID
          SecurityGroupIds:
            - !Ref BatchComputeEnvironmentSecurityGroup
          Type: FARGATE_SPOT
      ReplaceComputeEnvironment: true
      State: ENABLED
      Tags: 
        xhunt : task-cluster
      Type: MANAGED


  BatchComputeEnvironmentSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: Security group for batch compute environment
      GroupName: XHuntBatchComputeEnvironment
      SecurityGroupEgress: 
        - Description: Allow all egress   
          CidrIp: 0.0.0.0/0
          IpProtocol: -1
      Tags: 
        - Key: xhunt
          Value: task-cluster
      VpcId: !Ref ClusterVPCID

  
  ECSTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      RoleName: XHuntECSTaskClusterExecutionRole
      Tags:
        - Key: xhunt
          Value: task-cluster

  JobQueue:
    Type: AWS::Batch::JobQueue
    Properties: 
      ComputeEnvironmentOrder: 
        - ComputeEnvironment: !GetAtt BatchComputeEnvironment.ComputeEnvironmentArn
          Order: 1
      JobQueueName: XHuntTaskClusterJobQueue
      Priority: 1
      State: ENABLED
      Tags: 
        xhunt : task-cluster

Outputs:
  XHuntTaskClusterJobQueueARN:
    Value: !Ref JobQueue
    Export:
      Name: XHuntTaskClusterJobQueueARN