AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  job-dispatcher

  Sample SAM Template for job-dispatcher

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 180

Parameters:
  DeploymentEnvironment:
    Type: String
    Description: The environment you are deploying this stack in.
  ClusterSubnetID:
    Type: String
    Default: subnet-24a5095e
    Description: Enter the subnet ID you wish to deploy this cluster in.
  ClusterVPCID:
    Type: String
    Default: vpc-5475173c
    Description: >
      Enter the VPC ID you wish to deploy this cluster in. The default VPC is recommended.
      This is done so that a security group can be deployed.
  DynamoDBSubdomainsTableStreamARN:
    Type: String
    Description: Subdomains dynamodb table to subscribe to to process.


Resources:
  DalfoxUrlJobDispatcherServerlessApplication:
    Type: AWS::Serverless::Application
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Properties:
      Location: dalfox_url_job_dispatcher/template.yaml
      Parameters:
        DalfoxUrlsQueueName: !GetAtt DalfoxUrlsQueue.QueueName
        ECSTaskExecutionRoleARN: !GetAtt ECSTaskExecutionRole.Arn
        XHuntToolsContainerRepositoryName: !Ref XHuntToolsRepository
        JobQueue: !Ref JobQueue
  
  GauSubdomainJobDispatcherServerlessApplication:
    Type: AWS::Serverless::Application
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Properties:
      Location: gau_subdomain_job_dispatcher/template.yaml
      Parameters:
        DeploymentEnvironment: !Ref DeploymentEnvironment
        DynamoDBSubdomainsTableStreamARN: !Ref DynamoDBSubdomainsTableStreamARN
        DalfoxUrlsQueueUrl: !GetAtt DalfoxUrlsQueue.QueueUrl
        DalfoxUrlsQueueArn: !GetAtt DalfoxUrlsQueue.Arn
        ArjunParameterMiningQueueUrl: !GetAtt ArjunParameterMiningQueue.QueueUrl
        SubdomainUrlsDbWriterQueueArn: !GetAtt SubdomainUrlsDbWriterQueue.Arn
        SubdomainUrlsDbWriterQueueUrl: !GetAtt SubdomainUrlsDbWriterQueue.QueueUrl
        ECSTaskExecutionRoleARN: !GetAtt ECSTaskExecutionRole.Arn
        XHuntToolsContainerRepositoryName: !Ref XHuntToolsRepository
        JobQueue: !Ref JobQueue

  ArjunParameterMiningJobDispatcherServerlessApplication:
    Type: AWS::Serverless::Application
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Properties:
      Location: arjun_parameter_mining_job_dispatcher/template.yaml
      Parameters:
        DeploymentEnvironment: !Ref DeploymentEnvironment
        ArjunParameterMiningQueueName: !GetAtt ArjunParameterMiningQueue.QueueName
        DalfoxUrlsQueueUrl: !GetAtt DalfoxUrlsQueue.QueueUrl
        DalfoxUrlsQueueArn: !GetAtt DalfoxUrlsQueue.Arn
        ECSTaskExecutionRoleARN: !GetAtt ECSTaskExecutionRole.Arn
        XHuntToolsContainerRepositoryName: !Ref XHuntToolsRepository
        JobQueue: !Ref JobQueue
        
  SubdomainUrlsDbWriterServerlessApplication:
    Type: AWS::Serverless::Application
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Properties:
      Location: subdomain_urls_db_writer/template.yaml
      Parameters:
        SubdomainUrlsTableName: !Ref SubdomainUrlsDynamoDBTable
        SubdomainUrlsDbWriterQueueArn: !GetAtt SubdomainUrlsDbWriterQueue.Arn

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Join:
        - ''
        - - ApplicationInsights-SAM-
          - Ref: AWS::StackName
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0

  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Fn::Join:
        - ''
        - - ApplicationInsights-SAM-
          - Ref: AWS::StackName
      AutoConfigurationEnabled: 'true'
    DependsOn: ApplicationResourceGroup

  ## DATABASES ##
  SubdomainUrlsDynamoDBTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TableName: SubdomainUrls
      AttributeDefinitions:
      - AttributeName: sub_domain
        AttributeType: S
      - AttributeName: url
        AttributeType: S
      - AttributeName: time
        AttributeType: N
      KeySchema:
      - AttributeName: sub_domain
        KeyType: HASH
      - AttributeName: url
        KeyType: RANGE
      LocalSecondaryIndexes:
        - IndexName: index_by_time
          KeySchema:
            - AttributeName: sub_domain
              KeyType: HASH
            - AttributeName: time
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      StreamSpecification:
        StreamViewType: NEW_IMAGE
      BillingMode: PAY_PER_REQUEST

  ## QUEUES ##
  ## DALFOX URLS ##
  DalfoxUrlsQueue:
    Type: AWS::SQS::Queue
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Properties:
      VisibilityTimeout: 180
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt DalfoxUrlsDeadLetterQueue.Arn
        maxReceiveCount: 3
      QueueName: DalfoxUrlsQueue
      Tags:
        - 
          Key: xhunt-infrastructure
          Value: !Ref AWS::StackId

  DalfoxUrlsDeadLetterQueue:
    Type: AWS::SQS::Queue
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Properties:
      VisibilityTimeout: 160
      QueueName: DalfoxUrlsDeadLetterQueue
      Tags:
        -
          Key: xhunt-infrastructure
          Value: !Ref AWS::StackId

  DalfoxUrlsQueueAgeOfOldestMessage:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: DalfoxUrlsQueue_AgeOfOldestMessage
      AlarmDescription: Alarms if the SQS Queue has messages in it for too long
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: QueueName
          Value: !GetAtt DalfoxUrlsQueue.QueueName
      DatapointsToAlarm: 2
      EvaluationPeriods: 3
      MetricName: ApproximateAgeOfOldestMessage
      Namespace: AWS/SQS
      Period: 300
      Statistic: Maximum
      Threshold: 30
      TreatMissingData: notBreaching
      Unit: Seconds

  DalfoxUrlsDeadLetterQueueApproximateNumberOfMessagesVisible:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: DalfoxUrlsDeadLetterQueue_ApproximateNumberOfMessagesVisible
      AlarmDescription: Alarms if the Dead Letter Queue has too many messages
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: QueueName
          Value: !GetAtt DalfoxUrlsDeadLetterQueue.QueueName
      DatapointsToAlarm: 2
      EvaluationPeriods: 3
      MetricName: ApproximateNumberOfMessagesVisible
      Namespace: AWS/SQS
      Period: 300
      Statistic: Maximum
      Threshold: 1
      TreatMissingData: notBreaching

  ## ARJUN PARAMETER MINING QUEUE ##
  ArjunParameterMiningQueue:
    Type: AWS::SQS::Queue
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Properties:
      VisibilityTimeout: 180
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt ArjunParameterMiningDeadLetterQueue.Arn
        maxReceiveCount: 3
      QueueName: ArjunParameterMiningQueue
      Tags:
        - 
          Key: xhunt-infrastructure
          Value: !Ref AWS::StackId

  ArjunParameterMiningDeadLetterQueue:
    Type: AWS::SQS::Queue
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Properties:
      VisibilityTimeout: 160
      QueueName: ArjunParameterMiningDeadLetterQueue
      Tags:
        -
          Key: xhunt-infrastructure
          Value: !Ref AWS::StackId

  ArjunParameterMiningAgeOfOldestMessage:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: ArjunParameterMining_AgeOfOldestMessage
      AlarmDescription: Alarms if the SQS Queue has messages in it for too long
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: QueueName
          Value: !GetAtt ArjunParameterMiningQueue.QueueName
      DatapointsToAlarm: 2
      EvaluationPeriods: 3
      MetricName: ApproximateAgeOfOldestMessage
      Namespace: AWS/SQS
      Period: 300
      Statistic: Maximum
      Threshold: 30
      TreatMissingData: notBreaching
      Unit: Seconds

  ArjunParameterMiningDeadLetterQueueApproximateNumberOfMessagesVisible:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: ArjunParameterMiningDeadLetterQueue_ApproximateNumberOfMessagesVisible
      AlarmDescription: Alarms if the Dead Letter Queue has too many messages
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: QueueName
          Value: !GetAtt ArjunParameterMiningDeadLetterQueue.QueueName
      DatapointsToAlarm: 2
      EvaluationPeriods: 3
      MetricName: ApproximateNumberOfMessagesVisible
      Namespace: AWS/SQS
      Period: 300
      Statistic: Maximum
      Threshold: 1
      TreatMissingData: notBreaching

  ## SUBDOMAIN URLS DB WRITER QUEUE ##
  SubdomainUrlsDbWriterQueue:
    Type: AWS::SQS::Queue
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Properties:
      VisibilityTimeout: 180
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt SubdomainUrlsDbWriterDeadLetterQueue.Arn
        maxReceiveCount: 3
      QueueName: SubdomainUrlsDbWriterQueue
      Tags:
        - 
          Key: xhunt-infrastructure
          Value: !Ref AWS::StackId

  SubdomainUrlsDbWriterDeadLetterQueue:
    Type: AWS::SQS::Queue
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Properties:
      VisibilityTimeout: 160
      QueueName: SubdomainUrlsDbWriterDeadLetterQueue
      Tags:
        -
          Key: xhunt-infrastructure
          Value: !Ref AWS::StackId

  SubdomainUrlsDbWriterQueueAgeOfOldestMessage:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: SubdomainUrlsDbWriterQueue_AgeOfOldestMessage
      AlarmDescription: Alarms if the SQS Queue has messages in it for too long
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: QueueName
          Value: !GetAtt SubdomainUrlsDbWriterQueue.QueueName
      DatapointsToAlarm: 2
      EvaluationPeriods: 3
      MetricName: ApproximateAgeOfOldestMessage
      Namespace: AWS/SQS
      Period: 300
      Statistic: Maximum
      Threshold: 30
      TreatMissingData: notBreaching
      Unit: Seconds

  SubdomainUrlsDbWriterDeadLetterQueueApproximateNumberOfMessagesVisible:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: SubdomainUrlsDbWriterDeadLetterQueue_ApproximateNumberOfMessagesVisible
      AlarmDescription: Alarms if the Dead Letter Queue has too many messages
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: QueueName
          Value: !GetAtt SubdomainUrlsDbWriterDeadLetterQueue.QueueName
      DatapointsToAlarm: 2
      EvaluationPeriods: 3
      MetricName: ApproximateNumberOfMessagesVisible
      Namespace: AWS/SQS
      Period: 300
      Statistic: Maximum
      Threshold: 1
      TreatMissingData: notBreaching

  ## ECR ##
  XHuntToolsRepository:
    Type: AWS::ECR::Repository
    Properties: 
      RepositoryName: xhunt-tools
      ImageScanningConfiguration: 
        ScanOnPush: true

  ## FARGATE CLUSTER ##
  BatchComputeEnvironment:
    Type: AWS::Batch::ComputeEnvironment
    Properties: 
      ComputeEnvironmentName: XHuntTaskComputeEnvironment
      ComputeResources:
          MaxvCpus: 16
          Subnets: 
            - !Ref ClusterSubnetID
          SecurityGroupIds:
            - !Ref BatchComputeEnvironmentSecurityGroup
          Type: FARGATE_SPOT
      ReplaceComputeEnvironment: true
      State: ENABLED
      Tags: 
        xhunt : task-cluster
      Type: MANAGED


  BatchComputeEnvironmentSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: Security group for batch compute environment
      GroupName: XHuntBatchComputeEnvironment
      SecurityGroupEgress: 
        - Description: Allow all egress   
          CidrIp: 0.0.0.0/0
          IpProtocol: -1
      Tags: 
        - Key: xhunt
          Value: task-cluster
      VpcId: !Ref ClusterVPCID

  
  ECSTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/service-role/AWSLambdaSQSQueueExecutionRole
      RoleName: !Sub XHuntECSTaskClusterExecutionRole-${DeploymentEnvironment}
      Tags:
        - Key: xhunt
          Value: task-cluster

  JobQueue:
    Type: AWS::Batch::JobQueue
    Properties: 
      ComputeEnvironmentOrder: 
        - ComputeEnvironment: !GetAtt BatchComputeEnvironment.ComputeEnvironmentArn
          Order: 1
      JobQueueName: XHuntTaskClusterJobQueue
      Priority: 1
      State: ENABLED
      Tags: 
        xhunt : task-cluster

  ## AUTOBB INTEROPERABILITY ##
  AutoBBSubdomainUrlsARNSSM:
    Type: AWS::SSM::Parameter
    Properties:
      Description: The ARN representing the SubdomainUrls table for the autobb client
      Name: subdomain-urls-table-arn
      Tags: 
        xhunt: legacy-interoperability
      Type: String
      Value: !GetAtt SubdomainUrlsDynamoDBTable.Arn


Outputs:
  XHuntTaskClusterJobQueueARN:
    Value: !Ref JobQueue
    Export:
      Name: XHuntTaskClusterJobQueueARN