version: 0.2

env:
  shell: bash
  variables:
    AWS_REGION: ca-central-1
    ECR_REPOSITORY: xhunt-ecr

proxy:
  upload-artifacts: yes
  logs: yes

phases:
  install:
    on-failure: ABORT
    runtime-versions:
      python: 3.10
  pre_build:
    on-failure: ABORT
    commands:
      - apt-get update
      - apt-get install -y docker.io
      - pip install --upgrade pip
      - pip install awscli
      - pip install cfn-lint
  build:
    on-failure: ABORT
    commands:
      - cfn-lint cloudformation/*.yaml
      - docker build -t 
