version: 0.2

env:
  shell: bash
  variables:
    AWS_REGION: ca-central-1
    ECR_REPOSITORY: xhunt-ecr

proxy:
  upload-artifacts: yes
  logs: yes

phases:
  install:
    on-failure: ABORT
    runtime-versions:
      python: 3.10
  pre_build:
    on-failure: ABORT
    commands:
      - source ./deploy.sh
      - pip install --upgrade pip
      - pip install awscli cfn-lint
      - cfn-lint cloudformation/ecr/*.yaml
  build:
    on-failure: ABORT
    commands:
      - docker build -t xhunt:latest .
  post_build:
    on-failure: ABORT
    commands:
      - xhunt-build-push-container