AWSTemplateFormatVersion: 2010-09-09
Description: Elastic Container Registory Repository using Cloudformation

Resources:
  XHuntTools:
    Type: AWS::ECR::Repository
    Properties: 
      RepositoryName: xhunt-tools
      ImageScanningConfiguration: 
        ScanOnPush: true
