AWSTemplateFormatVersion: 2010-09-09
Description: Elastic Container Registory Repository using Cloudformation

Parameters:
  RepoName: 
    Description: Name for ecr repo 
    Type: String

Resources:
  ECRRepo:
    Type: AWS::ECR::Repository
    Properties: 
      RepositoryName: !Sub ${RepoName}-repo
      ImageScanningConfiguration: 
        ScanOnPush: true

Outputs:
  RepoName:
    Value: !Ref RepoName
    Export:
      Name: RepoName