AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  job-dispatcher

  Sample SAM Template for job-dispatcher

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 180

Resources:
  JobDispatcherFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: job_dispatcher_function
      Handler: job_dispatcher/app.lambda_handler
      Runtime: python3.9
      Architectures:
      - x86_64
      Policies: AWSLambdaSQSQueueExecutionRole
      Environment:
        Variables:
            TASK_CLUSTER_JOB_QUEUE_ARN: !ImportValue XHuntTaskClusterJobQueueARN
            TASK_CLUSTER_REFLECTED_XSS_JOB_DEFINITION_ARN: !ImportValue XHuntTaskClusterJobDefinitionARN

      # Configure event source mappings
      # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-function-sqs.html
      Events:
        ReflectedXSSUrlsQueue:
          Type: SQS
          Properties:
            Enabled: true
            Queue: !Sub 'arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:${SQSQueue.QueueName}'

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Join:
        - ''
        - - ApplicationInsights-SAM-
          - Ref: AWS::StackName
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0

  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Fn::Join:
        - ''
        - - ApplicationInsights-SAM-
          - Ref: AWS::StackName
      AutoConfigurationEnabled: 'true'
    DependsOn: ApplicationResourceGroup

  # Topic to subscribe to
  ReflectedXSSUrlsSNSTopic:
    Type: AWS::SNS::Topic
    Properties: 
      DisplayName: "Reflected XSS SNS Topic"
      FifoTopic: false
      #Subscription: 
      #  - TODO
      Tags: 
        - 
          Key: xhunt-infrastructure
          Value: !Ref AWS::StackId
      TopicName: ReflectedXSSUrlsSNSTopic

  # Parameter for queue name in case we need to update it
  # Containers will reference this paramter to read messages from the queue
  ReflectedXSSUrlsQueueIdParameter:
    Type: AWS::SSM::Parameter
    Properties: 
      Description: ARN for reflected XSS URLs queue
      Name: reflected-xss-urls-queue
      Type: String
      Value: !Ref SQSQueue
      Tags:
        xhunt-infrastructure: !Ref AWS::StackId

  SQSQueue:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 180
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt ReflectedXSSUrlsDeadLetterQueue.Arn
        maxReceiveCount: 3
      QueueName: ReflectedXSSUrlsQueue
      Tags:
        - 
          Key: xhunt-infrastructure
          Value: !Ref AWS::StackId

  SQSQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref SQSQueue
      PolicyDocument:
        Id: AllowIncomingAccess
        Statement:
          -
            Effect: Allow
            Principal:
              AWS:
                - !Ref AWS::AccountId
            Action:
              - sqs:SendMessage
              - sqs:ReceiveMessage
            Resource:
              - !GetAtt SQSQueue.Arn
          -
            Effect: Allow
            Principal: '*'
            Action:
              - sqs:SendMessage
            Resource:
              - !GetAtt SQSQueue.Arn
            Condition:
              ArnEquals:
                aws:SourceArn: !Ref ReflectedXSSUrlsSNSTopic

  ReflectedXSSUrlsDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 160
      QueueName: ReflectedXSSUrlsDeadLetterQueue
      Tags:
        -
          Key: xhunt-infrastructure
          Value: !Ref AWS::StackId

  SNSSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref ReflectedXSSUrlsSNSTopic
      Endpoint: !GetAtt SQSQueue.Arn
      Protocol: sqs
      RawMessageDelivery: true

  SQSQueueAgeOfOldestMessage:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: SQSQueue_AgeOfOldestMessage
      AlarmDescription: Alarms if the SQS Queue has messages in it for too long
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: QueueName
          Value: !GetAtt SQSQueue.QueueName
      DatapointsToAlarm: 2
      EvaluationPeriods: 3
      MetricName: ApproximateAgeOfOldestMessage
      Namespace: AWS/SQS
      Period: 300
      Statistic: Maximum
      Threshold: 30
      TreatMissingData: notBreaching
      Unit: Seconds

  ReflectedXSSUrlsDeadLetterQueueApproximateNumberOfMessagesVisible:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: ReflectedXSSUrlsDeadLetterQueue_ApproximateNumberOfMessagesVisible
      AlarmDescription: Alarms if the Dead Letter Queue has too many messages
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: QueueName
          Value: !GetAtt ReflectedXSSUrlsDeadLetterQueue.QueueName
      DatapointsToAlarm: 2
      EvaluationPeriods: 3
      MetricName: ApproximateNumberOfMessagesVisible
      Namespace: AWS/SQS
      Period: 300
      Statistic: Maximum
      Threshold: 1
      TreatMissingData: notBreaching

  # SQS Execution Role
  SQSExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: XHuntJobDispatcherSQSExecutionRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          -
            Effect: 'Allow'
            Principal:
              Service:
                - 'lambda.amazonaws.com'
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaSQSQueueExecutionRole


Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  JobDispatcherFunction:
    Description: Job Dispatcher Lambda Function ARN
    Value: !GetAtt JobDispatcherFunction.Arn

  # SQS
  SQSQueueArn:
    Value: !GetAtt SQSQueue.Arn
